### ISSUE TITLE
Need to find a solution for the alpha issue; not using blending

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react#18]
(issue to follow https://github.com/ProjectSeptemberInc/gl-react-native/issues/12 )

## Problem

The problem we are facing is trying to solve this:

![](https://pbs.twimg.com/media/CPu7qiDWsAA4i4i.png)

this is the result of a pipeline a chain of N "Copy" shader framebuffers (that just copy a texture). And we do this on an [image](http://i.imgur.com/mp79p5T.png) with a gradient of opacity values on top of [another image](http://i.imgur.com/S22HNaU.png). Fact is we observe a reduction of the alpha values (like if alpha is multiplying itself. `80% x 80% = 64%` , ...).

This result occurs when doing a classical:

`gl.clearFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)`

## First solution attempted

A solution is explained here: http://stackoverflow.com/a/18497511/343892 (answering this same problem).
It involves doing `gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);` with premultiplied texture.

and i've tried to implement it. **It works**, but now there is two big downside:

### 1. it is not reliable at all in WebGL world...
Because to make it possible, I need to create the WebGL context with `{ premultipliedAlpha: false }` option (which is not the default), and it does not work everywhere... [As mentioned here](http://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html), premultiplied alpha is enabled by default in WebGL and [as mentioned here](https://github.com/brianchirls/Seriously.js/commit/95e4eec0e54628c97f85dd927ca4344379635d5b), the premultipliedAlpha WebGL option is not stable across browser implementation since "this option is optional and it is not feature-detectable".

### 2. shaders have to be premultiplied

This method only relies on using premultiplied alpha textures which means textures that have **their RGB components multiplied by the A component**.
This is also true for "fbo textures" that have been rendered by a shader.

using this "non standard" blending method, any "generic" shader will have to adapt to make itself "premultiplied". (if using transparency)

Now a solution I've found is to not change it on the shader side, but introducing a new props (option) to make a specific pipeline effect using the classical `gl.SRC_ALPHA` instead.

This makes everything more complicated now...

## Help wanted

So we are back at the beginning for this problem. I like to keep as few variation as possible from a default WebGL settings, so I wish to find a solution for this initial problem without involving esoteric blending modes.

PS: the solution introduced here "works" in the react-native iOS implementation but i'm not so sure it works across all devices (since blending is generally a more advanced feature of OpenGL) and not sure it will also work in a future Android version. So I wish to move it to more standard approach too.

**Comment by gre** [comment]
no one seems to have an answer for this. We will probably go with current solution + a feature-detection (I think we can feature detect it by drawing in a 1 x 1 canvas) and fallback on classic method that won't properly support stack of effects using alpha.

**Comment by mattdesl** [comment]
what about `context.getContextAttributes()` to see if the value you set in `getContext('webgl', ..)` has been kept?

It would be worth testing to see what the support is like. I feel like most devices support `premultipliedAlpha: false`.

**Comment by gre** [comment]
I need to give another try but Safari is saying `premultipliedAlpha: false` but behaves as if it does not support it.

**Comment by greggman** [comment]
I'm not understanding the issue you're trying to solve. Let's assume I have a pixel `s` with an alpha of 0.5

    d.a = 1
    d = (s * s.a) + (d - (1 - s.a)  // blend 

now `d.a = 0.5` So I blend again I'm starting with `d.a = 0.5` which means

    // 2nd time
    d.a = 0.5 // from last pass
    d = (s * s.a) + (d - (1 - s.a)  // blend 

    d.a = 0.25

I guess I need to see what you're doing. As for { premultipliedAlpha: false } not working you can just clear the alpha to 1

    // render everything how ever you want
    render():

    // set the alpha to 1
    gl.clearColor(1, 1, 1, 1);
    gl.colorMask(false, false, false, true);
    gl.clear(gl.COLOR_BUFFER_BIT);
    gl.colorMask(false, false, false, false);

**Comment by gre** [comment]
Hi @greggman , thanks for you help, I think you have just helped me a lot on this!

So far, I assumed that this shader was **identity** (using the classic blend):

```glsl
precision highp float;
varying vec2 uv;
uniform sampler2D t;
void main () {
  gl_FragColor = texture2D(t, uv);
}
```

**but I was wrong, it is not**, I didn't expect the alpha to also be multiplied in the blend formula.

I need to re-read the API doc, reconsider all the example, see if I can find a solution also using your `gl.colorMask(false, false, false, true);`.

Also, yes I will try to provide a minimal example to try to reproduce it so I can submit some bugs ;)

Thanks!

**Comment by gre** [comment]
I think this is not anymore an issue then.. We will just deal with this fact.

It seems that in the context of `gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)`,
we can do identity with:
```glsl
precision highp float;
varying vec2 uv;
uniform sampler2D t;
void main () {
  vec4 c = texture2D(t, uv);
  gl_FragColor = c / sqrt(c.a);
}
```

however, in a `texture -> copy* -> webgl canvas` pipeline, it does "unblend" one time too much:

<img width="1003" alt="screen shot 2015-09-30 at 13 20 48" src="https://cloud.githubusercontent.com/assets/211411/10191647/1cc3a1b4-6776-11e5-8c21-509bd0e299e2.png">

(first test is the reference, `<img>` over another `<img>`, following tests are doing `<canvas>` over `<img>` and where the canvas have from 1 to 4 `copy` shader in the pipeline)


Anyway, since this alpha composition feature is probably < 20% use-cases, we will just rollback to this default, and users will have to deal with this default behavior.

Thanks all
