### ISSUE TITLE
Support for grabbing the output from GL

### ISSUE THREAD

**Issue by tjpotts** [ProjectSeptemberInc/gl-react#19]
I'm trying to give users in my a app a button to download the output from a gl canvas. I'm doing this by grabbing the canvas DOM element and using `canvas.toDataURL()`. However, this results in a blank image (even though the canvas is not blank).

The reason for this, as well as two possible fixes is explained in [this SO question](http://stackoverflow.com/questions/12538193/why-does-my-canvas-go-blank-after-converting-to-image). Basically, either set `preserveDrawingBuffer: true` when you create the GL context, or grab the image using `canvas.toDataUrl()` immediately after drawing, before control is returned to the browser.

It would be nice if there was either an option to set a `preserveDrawingBuffer` option (i.e. on `GL.View`, similar to the `opaque` option), or tell `gl-react` to save a copy of the output somewhere after every render so that you can grab it later. I suppose another possibility would be to allow for an optional callback which is called directly after every render, so that it can be done manually.

**Comment by gre** [comment]
Will be in incoming 1.1.0 :)

**Comment by gre** [comment]
```
render() {
  return <GL.View ref="view" ... />;
}

capture () {
  this.refs.view.captureFrame(data64 => ...);
}
```

The callback approach was a good candidate to be implemented later in gl-react-native (we also have the same use-case in RN context ;) ).
