### ISSUE TITLE
inject previous buffer as a texture

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react#25]
We need a way to inject the previous buffer as a texture. **usecase: persistence effect (motion blur)**

This is a solution to address https://github.com/ProjectSeptemberInc/gl-react-native/issues/19

### API

First idea: `<GL.View ... uniforms={{ backbuffer: GL.DrawingBuffer }} />`

Second idea (more generic): `<GL.View saveBuffer="foo" ... uniforms={{ backbuffer: GL.fromBuffer("foo") }} />`

**Comment by gre** [comment]
more generic way:

`<GL.View saveBuffer="foo"  ...  uniforms={{ backbuffer: GL.fromBuffer("foo") }} />`

**Comment by gre** [comment]
implementers will have to use special framebuffer that are preserved after each render. This new collection of framebuffers should be solved by the core impl. in gl-react-native impl, the fbos are shared, so that means we need a separated collection of fbos that belong to each view. We then need a new internal format to describe where the fbo belong (maybe we can have a fboType field that is either "shared" or "preserved")

**Comment by gre** [comment]
closing this dup in favor of #27

**Comment by ptmt** [comment]
Awesome!
