### ISSUE TITLE
Expose gl.viewport 

### ISSUE THREAD

**Issue by Maxoos** [ProjectSeptemberInc/gl-react#31]
This is a great project, saved me so much time and effort.

It would be nice to have a way to control the viewport, a good use case would be a canvas that fills the whole page. You can set the canvas to window width and height and then change the viewport to make sure the image will fill the frame and keep the ratio.

Thanks!

**Comment by gre** [comment]
why not using a `GL.View` with the viewport size you want that you put inside a `<div>` that takes the full window size?

Not sure how related it is to your need but eventually we should support custom vertex shader & custom data https://github.com/ProjectSeptemberInc/gl-react/issues/6

**Comment by gre** [comment]
I think it's up to user to solve the ratio problem, it can be solved by using a Surface inside View / div container.
A new feature recently land that allows to do things like this:

<Surface width={200} height={200}>
  <HelloGL width={20} height={20} />
</Surface>

in this code, the HelloGL node will be render on a 20x20 framebuffer and auto-scaled to the Surface's 200x200. It's up to the user to deal with the Surface width and height and making it fit to the size used in HelloGL for instance.
