### ISSUE TITLE
Undefined _fingGLNodeGLComponent

### ISSUE THREAD

**Issue by antoxi4** [ProjectSeptemberInc/gl-react#39]
Hey, i try use gl-react on react native. I wrote a test application looking at your examples. And writes this error. 
undefined is not an object(evaluating '_findGLNodeInGLCompon.via')

**Comment by gre** [comment]
This means you have put nothing (or a non valid object) inside your `<GL.Surface>`, i've updated the gl-react lib to make this error case not crashing like this.

see https://projectseptemberinc.gitbooks.io/gl-react/content/docs/api/Surface.html
