### ISSUE TITLE
Better error message for wrong import

### ISSUE THREAD

**Issue by DanielMSchmidt** [ProjectSeptemberInc/gl-react#40]
Hi there,

I just began using your lib and it seems pretty great by now. One Feedback I would like to give is that the error message mentioned in #32 and displayed [here](https://github.com/ProjectSeptemberInc/gl-react/blob/master/src/react-runtime.js#L21) was not very helpful at the first moment. I had to search for this error in the project, I think having [this part](https://github.com/ProjectSeptemberInc/gl-react/blob/master/src/react-runtime.js#L4-L19) as error message would have helped me to understand even faster what I did wrong.

Hope your project stays as cool as it is, Happy Holidays!

**Comment by gre** [comment]
You should have a warning message logged in the console too. that said, it's still good to clarify the error thrown, will work on it
