### ISSUE TITLE
Not working with electron-react-boilerplate

### ISSUE THREAD

**Issue by morukutsu** [ProjectSeptemberInc/gl-react#48]
Hi, first thanks you for your awesome project :+1: 

I've been experimenting with gl-react and electron-react-boilerplate (https://github.com/chentsulin/electron-react-boilerplate).
See this little example: https://github.com/morukutsu/electron-react-boilerplate/blob/master/app/containers/App.js

Running this code will produce an exception in events.js (Node.js related file, I think) in the addListener function line 220:
``` 
++this._eventsCount;
Uncaught TypeError: Cannot assign to read only property '_eventsCount' of #<Object>
````

The bug is caused by https://github.com/ProjectSeptemberInc/gl-react/blob/master/src/Shaders.js#L182 which exports an immutable Shaders object.
Then, here https://github.com/ProjectSeptemberInc/gl-react-dom/blob/master/src/compileShaders.js#L17 , an event is added to this object.

To quick fix it, I just removed the call to Object.freeze and it worked very well.

I don't know what the Javascript RFC says about adding an event to a frozen Object but I guess it violates the immutability assertion. Also, why does the error happens only in this environment, I did not test it in the browser yet. What do you think?

Thanks

**Comment by gre** [comment]
I'm OK to remove the freeze.
Can you provide a PR ?

Thanks
Le 26 janv. 2016 00:42, "Uldéric KIBONGUI" <notifications@github.com> a
écrit :

**Comment by morukutsu** [comment]
Okay, yes no problem, I'll submit it.
