### ISSUE TITLE
Support for vertex shader / custom buffer data

### ISSUE THREAD

**Issue by gre** [ProjectSeptemberInc/gl-react#6]
the vertex and buffer should NOT be hard coded by implementations but provided by gl-react-core (and defaulted if none is provided).

Something like:

```
var shaders = GL.Shaders.create({ shaderName: { frag, vert } });
// and then
<GL.View shader={shaders.shaderName} buffer={[ 1, 2, 3, 4, 5, /* whatever*/ ]} ...  />
```

This would allow more advanced use-cases (like 3D shapes).

Now giving more power means we have to be more generic and expose much more OpenGL things.
This might be challenging and we will have to identify a subset of use-cases to start with.

**Comment by mrspeaker** [comment]
Tough call... the problem I see is that right now it has a narrow focus on creating effects and filters via shaders. If we allow general vertex handling etc, then this needs to become a (not-too-leaky) abstraction over all of OpenGL. Which could be really cool, but is quite a different idea!

**Comment by gre** [comment]
yeah, true.

We could still provide a minimal support of vertex, but I get that this brings new responsability for the library and stuff to maintain. Also I don't think this change so much the focus, this just extends a bit more the genericity of the lib (removing hardcoded part from impls). This allows to be more generic and for instance integrating shaders that relies on different vertex shader.

Now the buffer thing is more tricky, but for use case that implies "static" buffer (like we could recreate this example I guess http://jlongster.com/First-Impressions-using-React-Native ), I think it should work great, but once there are dynamic shapes, this might be complex to make the descriptive approach performant.

Anyway, this library should be driven by use-case, so for now we focus on doing effects over content,
if someone later have another use case, we can discuss here.

Probably for now, we should focus on implementing remaining features / porting the implementation everywhere (Android)

**Comment by gre** [comment]
not our current focus. we can reopen if we figure out a simple use-case & an implementation plan.

**Comment by joewood** [comment]
I would like to see this. Maybe react-gl can act as a compositor library, exposing the vertex buffer and vertex shaders only. Then separate libraries can be used to create 2D and 3D primitives and common shaders.

**Comment by gre** [comment]
gl-react*

I definitely agree and it could allow much more use-case, it's a challenge though. We will probably keep pushing forward features on the "final part" of the pipeline (fragment shader) in a near future but I agree that on the long term we should investigate on ways to generalise gl-react more to move the "hardcoded cursor" to the left (in following diagram) and probably not having anything hardcoded :)

<img width="929" alt="screen shot 2016-02-24 at 18 17 00" src="https://cloud.githubusercontent.com/assets/211411/13304475/d35b6a68-db22-11e5-89ce-90bde6ff916a.png">

We are open to contribution too :) There are probably a bunch of things to figure out on how to implement this properly (especially on react-native) and how to provide a nice API on gl-react.

**Comment by lyssdod** [comment]
I highly vote for this. While I have no experience with ios programming, I do have experience with Linux/Android one, so I can try to implement VBO interface for react-native. Looking at https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html it seems that ios part shouldn't be much harder.

**Comment by gre** [comment]
The hard part is probably how to define and support a useful and consistent
API so you can fully use all features resulting of introducing vertex
shaders and data and continuing maintaining this so it's performant.

Unlocking this feature will make people start using it with huge vertex
model, so it have to be performant. I'm not sure the react-native bridge
will be fast enough. Especially there are no native array support.

So these are to be investigated, it's not our priority at the moment, but
for sure feel free to experiment on this and we accept PRs.
