### ISSUE TITLE
Any way to support Pixi.js?

### ISSUE THREAD

**Issue by jdnichollsc** [ProjectSeptemberInc/gl-react#62]
Hi guys!

Do you want support Pixi.js to use WebGL/Canvas easily?

Regards, Nicholls

**Comment by gre** [comment]
no I think if you want to use Pixi.js, you should use the library itself. You should be able to use `<canvas/>` yourself and setup a Component quite easily.

gl-react focus on maintaining a common API just on top of OpenGL/WebGL and allow writing shaders for things like image effects.
