### ISSUE TITLE
How to maintain aspect ratio of texture

### ISSUE THREAD

**Issue by dcworldwide** [ProjectSeptemberInc/gl-react#63]
When rendering a image as a texture to a surface, I've noticed that the aspect ratio is off. How do I preserve the aspect ratio? 

I've defined my surface as follows: 

```
<Surface ref={(img) => { this.img = img; }}
   width={Dimensions.get('window').width}
   height={310}>
  {activeFilter}
</Surface>
```

**Comment by gre** [comment]
sounds like it's exactly the reason why I wrote https://github.com/gre/gl-react-image this weekend :)

**Comment by dcworldwide** [comment]
Woo! Amazing :)

Is it possible to pass 1 or more gl image as uniforms to a shader?

Also assuming the surface export api still works? 

This library is really helping us out :)

**Comment by gre** [comment]
it's definitely possible. What do you mean by surface export api? the `captureFrame` Surface method? yes it will work.

```js
const image1source = { uri: ".../image1.png", width: ???, height: ??? };
const image2source = { uri: ".../image2.png", width: ???, height: ??? };

const Mix2 = GL.createComponent( ({ from, to, mix }) => ... );

<Mix2
  from={  <GLImage source={image1source} />  }
  to={  <GLImage source={image2source} />  }
  mix={0.5}
/>
```

**Comment by dcworldwide** [comment]
Cool that's great. Will upgrade my code this week and test it out 👍

**Comment by gre** [comment]
another alternative syntax is:

```js
const Mix2 = GL.createComponent( ({ children: [from, to], mix }) => ... );
<Mix2 mix={0.5}>
  <GLImage source={image1source} />
  <GLImage source={image2source} />
</Mix2>
```

but it's up to you ;)

**Comment by dcworldwide** [comment]
This worked perfectly for my use case, it's awesome work thanks again. 

I used this technique:

```
<Mix2
  from={  <GLImage source={image1source} />  }
  to={  <GLImage source={image2source} />  }
  mix={0.5}
/>
```
