### ISSUE TITLE
On AnimatedSurface don't work captureFrame() method

### ISSUE THREAD

**Issue by shahen94** [ProjectSeptemberInc/gl-react#64]
`<AnimatedSurface
        ref={surface => this.myFilter = surface}
        style={style}
        width={width}
        height={height}
      >
        {this.filterType()}
      </AnimatedSurface>`

When i call `this.myFilter.captureFrame() ` i get an error: 
`captureFrame() should be implemented by GLCanvas`

**Comment by gre** [comment]
good catch!

need to re-add all the static methods

**Comment by gre** [comment]
Released `gl-react-native 2.28.1`  and  `gl-react 2.2.5` that fix this

**Comment by shahen94** [comment]
@gre thank you so match
