### ISSUE TITLE
Y axis inverted?

### ISSUE THREAD

**Issue by stoffern** [ProjectSeptemberInc/gl-react#67]
@gre is there a reason why the y axis is inverted?
I did this project `gl-react-instagramfilters` and did a copy of the original GLSL code.
Then i discovered that the `gl-react` axis Y is inverted so i had to change the code.

**Comment by gre** [comment]
OpenGL have a different y-axis than most graphics standard unfortunately.
in OpenGL, y=0 is on the bottom and oriented up.

**Comment by gre** [comment]
can you point me more precisely where you have the problem occurring? it should be hidden by gl-react implementation unless you start doing image processing yourself (like filling up a buffer of pixel or something like this)

**Comment by stoffern** [comment]
This was the update to make it work with gl-react :
https://github.com/stoffern/gl-react-instagramfilters/commit/ddb4517df4fea42e6925dde6e87725ee2f00070c#diff-b022c19b0503009a86c27ab34a646671L15

It is all based on the original working code here:
https://github.com/danielgindi/Instagram-Filters

**Comment by gre** [comment]
mmh I see.
I guess they assume to have send the texture inversed so opengl understand it (or reversly, I can't even remember what convention gl-react has taken, but at least I made it consistent (if it's an image VS a snapshot))

unfortunately, this is the ugly part of OpenGL... everyone take its own convention and then it's hard to work together. (this is one problem, one other convention is how you blend the color.. there is different takes and not a single convention for this)

**Comment by gre** [comment]
I can't remember why I took the convention to accept only reversed texture (I should have written down a pro&con sorry), but i'm sure it was a tradeoff so it works everywhere (OpenGL / WebGL) in the gl-react usecases (a texture can be: an image, a view snapshot (ios / android), a video (web), a canvas (web), a **framebuffer** (this case is special, probably the reason of the convention)).

So this will probably won't change and you will have to fix it in GLSL I'm afraid.

**Comment by gre** [comment]
(framebuffer is what we use to do composition)

**Comment by stoffern** [comment]
:+1:  thanks for the answer. it makes sense :wink:
