### ISSUE TITLE
Shaders.setImplementation can be called only once

### ISSUE THREAD

**Issue by gevorg15** [ProjectSeptemberInc/gl-react#69]
After upgrading to RN 0.34 and gl-react 2.2.8 and gl-react-native 2.34.0, i'm getting an error from gl-react about Shaders.setImplementation.

<img width="376" alt="screen shot 2016-09-27 at 12 32 17 pm" src="https://cloud.githubusercontent.com/assets/569622/18888737/785822c4-84ae-11e6-970e-7653a6413df7.png">

It was working fine with RN 0.33 gl-react 2.2.6 and gl-react-native 2.33.0

**Comment by stoffern** [comment]
this is a gl-react-native issue
https://github.com/ProjectSeptemberInc/gl-react-native/pull/113

**Comment by gevorg15** [comment]
thanks, closing this issue. Created one at the gl-react-native repo. https://github.com/ProjectSeptemberInc/gl-react-native/issues/114
